### ISSUE TITLE
Feature request: Support conversion from GeoJSON to JSON records

### ISSUE THREAD

**Issue by miroli** [jplusplus/statscraper#2]
Some APIs return GeoJSON when the output format is set to JSON. The base library should probably handle the conversion to "regular" JSON, either in the form of a JSON blob with a list of records, or [NDJSON](http://ndjson.org/).

Example: http://resource.sgu.se/oppnadata/grundvatten/api/miljoovervakning/lan/{countycode}?format=[csv,json]

**Comment by rotsee** [comment]
Closing as out of scope, as we are primarily focusing on statistical, numerical data. Good idea, but will not happen anytime soon, anyway
